version: 2.1

orbs:
  trivy-orb: fifteen5/trivy-orb@1.0.0

jobs:
  build-image:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build Docker Image"
          command: "docker build -t michaelaviram/test ."
      - trivy/scan:
          args: "--no-progress --exit-code 1 image michaelaviram/test"

workflows:
  chaos-workflow:
    jobs:
      - build-image
