version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build Docker Image"
          command: "docker build -t registry.gitlab.com/michaelaviram-group/michaelaviram-project ."
      - run:
          name: Push image
          command: |
            echo "$GITLAB_PAT" | docker login "registry.gitlab.com" -u "michaelaviram" --password-stdin
            docker push registry.gitlab.com/michaelaviram-group/michaelaviram-project
workflows:
  chaos-workflow:
    jobs:
      - build-and-test
