version: 2.1
jobs:
  build-image:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build Docker Image"
          command: "docker build -t michaelaviram/test ."
      - run:
          name: Install Trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan image with trivy
          command: trivy --exit-code 0 --no-progress michaelaviram/test
workflows:
  chaos-workflow:
    jobs:
      - build-image
