version: 2.1

jobs:
  
  test:
    docker:
      - image: cimg/python:3.9.22
    steps:
      - checkout
      - run:
          name: test
          command: |
            pip install -r requirements.txt
            cd testing/
            pytest test_weather_unit.py
            pytest test_weather_integration.py
      - run:
          name: Notify Discord on Success
          when: on_success
          command: |
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"content": "Testing Succeeded!"}' \
                 $DISCORD_WEBHOOK
      - run:
          name: Notify Discord on Success
          when: on_fail
          command: |
            curl -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"content": "Testing Failed!"}' \
                 $DISCORD_WEBHOOK

  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build Docker Image"
          command: "docker build -t $GITLAB_REGISTRY/$GITLAB_GROUP/$GITLAB_PROJECT ."
      - run:
          name: Push image
          command: |
            echo "$GITLAB_PAT" | docker login "$GITLAB_REGISTRY" -u "$GITLAB_USERNAME" --password-stdin
            docker push $GITLAB_REGISTRY/$GITLAB_GROUP/$GITLAB_PROJECT

  checkov:
    docker:
      - image: bridgecrew/checkov:latest
    steps:
      - checkout
      - run:
          name: Install Checkov
          command: pip install -U checkov

      - run: 
          name: Run Checkov
          command: checkov --directory ./eks_tf/

workflows:
  chaos-workflow:
    jobs:
      - test
      - build:
          requires: 
            - test
      - checkov
