version: 2.1
jobs:
  build-image:
   docker:
     - image: cimg/base:current
   steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Immage
          command: docker build -t michaelaviram/test
workflows:
  chaos-workflow: 
  jobs:
      - build-image
